spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : true # sql 예쁘게 출력
    show-sql: true  # sql 출력


logging:
  level:
    org.hibernate.type: trace # sql binding 값 출력